CaraOnlineForms/Controllers/NavMenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModels;
using CaraEntites;

namespace CaraOnlineForms.Controllers
{
    public class NavMenuController : Controller
    {


        public PartialViewResult _NavMenu()
        {
            bool showMenu = new Session().User != null;
            return PartialView("_NavMenu", showMenu);
        }


        public PartialViewResult _WorkFlow(string StepId)
        {
            WorkFlowViewModel model = new WorkFlowViewModel { FilmTitle=null};
            FilmSubmission currentFilm = new Session().Film;
            if (currentFilm != null)
            {
                model.FilmSubmitionId = currentFilm.FilmSubmissionId;
                model.FilmTitle = currentFilm.FilmTitle;
                model.StepId = StepId;
            }
            return PartialView("_WorkFlow", model);
        }  
    }
}

CaraOnlineForms/Controllers/SummaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaraOnlineForms.Controllers
{
    public class SummaryController : Controller
    {
        //
        // GET: /Summary/

        public ActionResult Summary()
        {
            return View();
        }

    }
}

CaraOnlineForms/Views/Summary/Summary.cshtml
@using CaraEntites;
@using ViewModels;
@model CompaniesViewModel
@{
    ViewBag.Title = "Contacts";
    Html.RenderAction("_WorkFlow", "NavMenu", new { StepId = "Summary" });
}

<script>
    $(document).ready(function () {
        _cache = $('#frmSummary').serialize();
    });
</script>
<form id="frmSummary">
<h2>Summary</h2>
I'm here!!!
</form>