CaraOnlineForms/ViewModels/WorkFlowViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ViewModels
{
    public class WorkFlowViewModel
    {
        public int? FilmSubmitionId { get; set; }
        public string FilmTitle { get; set; }
        public string StepId { get; set; }
    }
}

CaraOnlineForms/Controllers/NavMenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModels;
using CaraEntites;

namespace CaraOnlineForms.Controllers
{
    public class NavMenuController : Controller
    {


        public PartialViewResult _NavMenu()
        {
            bool showMenu = new Session().User != null;
            return PartialView("_NavMenu", showMenu);
        }


        public PartialViewResult _WorkFlow(string StepId)
        {
            WorkFlowViewModel model = new WorkFlowViewModel { FilmTitle=null};
            FilmSubmission currentFilm = new Session().Film;
            if (currentFilm != null)
            {
                model.FilmSubmitionId = currentFilm.FilmSubmissionId;
                model.FilmTitle = currentFilm.FilmTitle;
                model.StepId = StepId;
            }
            return PartialView("_WorkFlow", model);
        }  
    }
}

CaraOnlineForms/Controllers/SubmitionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CaraEntites;
using Repository;

namespace CaraOnlineForms.Controllers
{
    public class SubmitionController : ControllerBase
    {

        
        public ActionResult Title(int? filmId)
        {
            FilmSubmission model = new FilmSubmission { FilmAltTitles = new List<FilmAltTitle>() };
            if (filmId == null) // new Title
            {
                this.CurrentFilm = null;
                return View(model);
            }

            model = new FilmRepository().GetFilm(filmId.Value, User.UserId);
            this.CurrentFilm = model; // save the selected film in session

            return View(model);
        }

        [HttpPost]
        public ActionResult SaveTitle(FilmSubmission film, List<string> AltTitle, string NextPage)
        {
            // UserID of the saved film must be taken from session
            film.UserId = this.User.UserId;
            
            // FilmID of the saved film also must be taken from  session 
            if (this.CurrentFilm != null) // else FilmId=0 (means new Film)
                film.FilmSubmissionId = this.CurrentFilm.FilmSubmissionId;

            FilmSubmission model =  new FilmRepository().SaveFilm(film, AltTitle.Where(x=>x!="").ToList(), this.User.UserId);

            //the saved film must be saved in session - now it's current film
            this.CurrentFilm = model;

            if (!String.IsNullOrEmpty( NextPage ) )
              return  Redirect(NextPage);

            ViewBag.Message = "The Title has been saved";
            return View("Title", model);
            
        }

    }
}

CaraOnlineForms/Views/Shared/_Error.cshtml
@model string
 <div class="validation-summary-errors">@Model</div>

CaraOnlineForms/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    <link href="@Url.Content("~/Content/superfish.css")" rel="stylesheet" type="text/css" media="screen" />
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    <link href="@Url.Content("~/Content/themes/redmond/jquery-ui-1.9.2.custom.css")" rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Scripts/superfish.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/hoverIntent.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.blockUI.js")" type="text/javascript"></script>
    <script src="@Url.Content("/Scripts/jQuery_AJAX_Custom.js")"></script>
    <script src="@Url.Content("/Scripts/jQuery_Styling_Custom.js")"></script>
    @RenderSection("scripts", required: false)
    <script>
        var _cache = null;
        var _beforeChanges = new Array();   //to keep serialyzed multiple forms (for now, from the "Rights Holders" page)

        function GoToNextPage(url) {

            $('form').first().remove(':hidden[name=NextPage]');

            if (url === undefined || url == '') {
                $('form').first().submit();
                return;
            }

            var callbackNo = function () {
                document.location.href = url;
            }

            var $frm = $('form').first();
            var dirtyFormId = "";
            var callbackYes;
            if (!/FormMailingContact/i.test($frm.attr('id'))) {  // if it is not "Rights Holders" page...
                callbackYes = function () {
                    if (url !== undefined || url != '') {
                        var nextPage = $('<input type="hidden" name="NextPage" />').attr('value', url);
                        $(nextPage).appendTo($('form').first());
                    }
                    $('form').first().submit();
                }
            }
            else {      // if it is "Rights Holders" page...
                var $frms = $('form');
                var i = 0;
                $frms.each(function () {         // loop through the forms to find out which one is edited
                    if (_beforeChanges[i] != $(this).serialize()) {
                        dirtyFormId = $(this).attr('id');
                    }
                    i++;
                });
                callbackYes = function () {
                    $("#" + dirtyFormId).find(".saveButton").focus();      //just set focus on the "Save" button
                }
            };
            
            if (_cache != $('form').first().serialize() || dirtyFormId != "") {  
                   confirmActionYesNoCancel("The current page has been modified.<br/>Woud You like save changes?", "Save changes?", "Yes", "No", callbackYes, callbackNo);
            } else {
                callbackNo();
            }

        }
    </script>
</head>
<body id="mvc">
    <div id="header">
        <div class="title ui-widget-header">
            <span>@ViewBag.PageHeader &nbsp; </span>
            <span id="loadingBar" style="width: 150px; color: White; height: 10px; display: none; left: 0px; top: 0px; padding: 0; margin: 0;">
                <img src="@Url.Content("~/Content/Images/busy.gif")"  alt=""/>
                &nbsp;loading...
            </span>
            <span class="NavMenu">
                @{Html.RenderAction("_NavMenu", "NavMenu", new { generationDate = DateTime.Now.ToString("MM/dd/yyyy hh:mm:ss.fff tt") }); }
            </span>
        </div>
    </div>
    <div id="wrap">
        @{ if (ViewBag.Message5 != null)
           {
            <div class="red">@ViewBag.Message</div>
            <div class="clear"></div>    
           }
        }
        @RenderBody()
        <div id="footer">
            <hr class="thinLine" />

            <div class="leftFloat">
                <img src="@Url.Content("~/Content/Images/MPAA_logo.png")" alt="MPAA, Inc." />
            </div>
            <div class="rightFloat lineHeight4em verticalCenterText">
                THE CLASSIFICATION & RATING ADMINISTRATION
            </div>
            <div class="clear"></div>
        </div>
    </div>
</body>
<script type="text/javascript">
    $(function () {
        // //style non-jqueryUI grid elements to look like jquery ui elements - globally
        //please note this will also hijax the 'href' on all links in header/footer, so it will only work through AJAX!
        jQueryUIStyling();

        jQuery('ul.sf-menu').superfish({ //style the nav menu
            delay: 800,                            //  delay on mouseout 
            animation: { opacity: 'show', height: 'show' },  // fade-in and slide-down animation 
            speed: 'slow',                          // faster animation speed 
            autoArrows: true,                           // disable generation of arrow mark-up 
            dropShadows: true                            // disable drop shadows 
        });

        jQuery(document).ajaxStart(function () {
            $("#loadingBar").fadeIn("fast");
        });
        jQuery(document).ajaxStop(function () {
            $("#loadingBar").fadeOut("fast");
        });
        jQuery(document).ajaxError(function () {
            $("wrap").fadeTo("fast", 1.0);
            $("#loadingBar").fadeOut("fast");
        });


        if ($('form').length > 0) {
            _cache = $('form').first().serialize();
        }
    })


</script>

</html>

CaraOnlineForms/Views/Shared/_NavMenu.cshtml
@model bool 
@if (Model)
{
<ul class="sf-menu">
      <li>
          <a href="@Url.Action("ProcessStatus","ProcessStatus")">Rating Process Status</a>
     </li>
     <li>
          <a href="@Url.Action("Title","Submition")">Submit a Motion Picture</a>
     </li>
     <li>
        <a href="#">My Info </a>
        <ul>
            <li class="sf-menu-current"><a href="@Url.Action("MyProfile","Account")">Profile</a></li>
            <li class="sf-menu-current"><a href="@Url.Action("ChangePassword","Account")">Change Password</a></li>
        </ul>
    </li>
</ul>
}

CaraOnlineForms/Views/Shared/_States.cshtml
@using ViewModels

@model CountryViewModel
@{
    var states = new List<SelectListItem>();
    states.Add(new SelectListItem { Value = "", Text = "" });
    states.Add(new SelectListItem { Value = "AL", Text = "ALABAMA" });
    states.Add(new SelectListItem { Value = "AK", Text = "ALASKA" });
    states.Add(new SelectListItem { Value = "AZ", Text = "ARIZONA" });
    states.Add(new SelectListItem { Value = "AR", Text = "ARKANSAS" });
    states.Add(new SelectListItem { Value = "CA", Text = "CALIFORNIA" });
    states.Add(new SelectListItem { Value = "CO", Text = "COLORADO" });
    states.Add(new SelectListItem { Value = "CT", Text = "CONNECTICUT" });
    states.Add(new SelectListItem { Value = "DE", Text = "DELAWARE" });
    states.Add(new SelectListItem { Value = "FL", Text = "FLORIDA" });
    states.Add(new SelectListItem { Value = "GA", Text = "GEORGIA" });
    states.Add(new SelectListItem { Value = "HI", Text = "HAWAII" });
    states.Add(new SelectListItem { Value = "ID", Text = "IDAHO" });
    states.Add(new SelectListItem { Value = "IL", Text = "ILLINOIS" });
    states.Add(new SelectListItem { Value = "IN", Text = "INDIANA" });
    states.Add(new SelectListItem { Value = "IA", Text = "IOWA" });
    states.Add(new SelectListItem { Value = "KS", Text = "KANSAS" });
    states.Add(new SelectListItem { Value = "KY", Text = "KENTUCKY" });
    states.Add(new SelectListItem { Value = "LA", Text = "LOUISIANA" });
    states.Add(new SelectListItem { Value = "ME", Text = "MAINE" });
    states.Add(new SelectListItem { Value = "MD", Text = "MARYLAND" });
    states.Add(new SelectListItem { Value = "MA", Text = "MASSACHUSETTS" });
    states.Add(new SelectListItem { Value = "MI", Text = "MICHIGAN" });
    states.Add(new SelectListItem { Value = "MN", Text = "MINNESOTA" });
    states.Add(new SelectListItem { Value = "MS", Text = "MISSISSIPPI" });
    states.Add(new SelectListItem { Value = "MO", Text = "MISSOURI" });
    states.Add(new SelectListItem { Value = "MT", Text = "MONTANA" });
    states.Add(new SelectListItem { Value = "NE", Text = "NEBRASKA" });
    states.Add(new SelectListItem { Value = "NV", Text = "NEVADA" });
    states.Add(new SelectListItem { Value = "NH", Text = "NEW HAMPSHIRE" });
    states.Add(new SelectListItem { Value = "NJ", Text = "NEW JERSEY" });
    states.Add(new SelectListItem { Value = "NM", Text = "NEW MEXICO" });
    states.Add(new SelectListItem { Value = "NY", Text = "NEW YORK" });
    states.Add(new SelectListItem { Value = "NC", Text = "NORTH CAROLINA" });
    states.Add(new SelectListItem { Value = "ND", Text = "NORTH DAKOTA" });
    states.Add(new SelectListItem { Value = "OH", Text = "OHIO" });
    states.Add(new SelectListItem { Value = "OK", Text = "OKLAHOMA" });
    states.Add(new SelectListItem { Value = "OR", Text = "OREGON" });
    states.Add(new SelectListItem { Value = "PA", Text = "PENNSYLVANIA" });
    states.Add(new SelectListItem { Value = "RI", Text = "RHODE ISLAND" });
    states.Add(new SelectListItem { Value = "SC", Text = "SOUTH CAROLINA" });
    states.Add(new SelectListItem { Value = "SD", Text = "SOUTH DAKOTA" });
    states.Add(new SelectListItem { Value = "TN", Text = "TENNESSEE" });
    states.Add(new SelectListItem { Value = "TX", Text = "TEXAS" });
    states.Add(new SelectListItem { Value = "UT", Text = "UTAH" });
    states.Add(new SelectListItem { Value = "VT", Text = "VERMONT" });
    states.Add(new SelectListItem { Value = "VA", Text = "VIRGINIA" });
    states.Add(new SelectListItem { Value = "WA", Text = "WASHINGTON" });
    states.Add(new SelectListItem { Value = "WV", Text = "WEST VIRGINIA" });
    states.Add(new SelectListItem { Value = "WI", Text = "WISCONSIN" });
    states.Add(new SelectListItem { Value = "WY", Text = "WYOMING" });
    
    if (Model.ISO.IsEmpty())
    {
        Model.ISO = "";
    }

    states.Find(x => x.Value == Model.ISO).Selected=true;
 }

@Html.DropDownList(@Model.Name, states)

CaraOnlineForms/Views/Shared/_WorkFlow.cshtml
@using ViewModels;
@model WorkFlowViewModel

@{
   
    
    var steps = new[] { 
        new { StepId = "Title", Label = "Picture Info", URL = Url.Action("Title", "Submition",new {filmId=Model.FilmSubmitionId }) },
        new { StepId = "Participants", Label = "Participants", URL = Url.Action("Participants", "Participants")},
        new { StepId = "Contacts", Label = "Right Holders", URL = Url.Action("GetMailingList", "Contacts",new {filmId=Model.FilmSubmitionId })},
        new { StepId = "Screener", Label = "Screener", URL = Url.Action("Screener", "Screener",new {filmId=Model.FilmSubmitionId })},
        new { StepId = "Company", Label = "Company/Contacts", URL = Url.Action("Companies", "Company",new {filmId=Model.FilmSubmitionId })},
        new { StepId = "Summary", Label = "Submit Picture", URL = Url.Action("Summary", "Summary")}
    };

    if (Model.FilmTitle != null)
    {
    @:<div>Title: @Model.FilmTitle</div>
       for (int i = 0; i < steps.Length; i++)
       {
           if (steps[i].StepId != Model.StepId)
           { 
    <div class="leftFloat labelRounded cursorPointer" style="display: inline"  onclick="GoToNextPage('@steps[i].URL')"><span>@steps[i].Label</span></div>
           }
           else
           {
    <div class="leftFloat labelRounded" style="display: inline; background-color: lightblue"><span>@steps[i].Label</span></div>
           }

           if (i < steps.Length - 1)
           {
    <div class="leftFloat" style="width: 20px; vertical-align: middle">
        <div style="border: 1px solid #7B99B7; border-top: hidden; border-left: hidden; border-right: hidden; height: 0.95em;">&nbsp;</div>
    </div>
           }

       }
    }
    <div class="clear"></div>
}
